### ISSUE TITLE
My Dashboard No working

### ISSUE THREAD

**Issue by leoanchique** [marcelotorres/redirect-after-login#6]
I migrated my site but now my admin doesn’t work. I enter the access data and he does not direct me to the dashboard, I tried to restart the .htaccess and it has not been possible I need urgent help.

The page I need help with: https://gutmedica.com.co/wp-login

**Comment by marcelotorres** [comment]
Hi @leoanchique, redirects you to which URL?

**Comment by leoanchique** [comment]
Marcelo Do you speak spanish?

Leonardo Andres Anchique Leal

________________________________
De : Marcelo Torres <notifications@github.com>
Envoyé : lundi 15 juillet 2019 20:49
À : marcelotorres/redirect-after-login
Cc : leoanchique; Mention
Objet : Re: [marcelotorres/redirect-after-login] My Dashboard No working (#6)


Hi @leoanchique<https://eur04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fleoanchique&data=02%7C01%7C%7C542e06f9045745c99beb08d709877943%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636988349763463997&sdata=SoWpJB3qZjpctnm0SIPPvZpyIZjEqB4MfsNdo1nKlFU%3D&reserved=0>, redirects you to which URL?

**Comment by marcelotorres** [comment]
I speak Portuguese, we can try the spanish or 'Portunhol' :D

**Comment by leoanchique** [comment]
Ok Marcelo i try speak in english.

Marcelo I did not develop the site. but i did the migration to another hosting.

https://gutmedica.com.co/wp-admin

the front-page  work well but the dashboard not working.

The people support say me is for the plugin redirect.

I try change de fille .htaccess but no working.

Could you look this issue if you use this data:

User: Optimo
Password: Leo0198*







Leonardo Andres Anchique Leal

________________________________
De : Marcelo Torres <notifications@github.com>
Envoyé : lundi 15 juillet 2019 21:06
À : marcelotorres/redirect-after-login
Cc : leoanchique; Mention
Objet : Re: [marcelotorres/redirect-after-login] My Dashboard No working (#6)


I speak Portuguese, we can try the spanish or 'Portunhol' :D

**Comment by marcelotorres** [comment]
@leoanchique don't send password here, send me for email please. I erased yout post.

**Comment by leoanchique** [comment]
Sorry could you send your email?

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by marcelotorres** [comment]
You already added me an email (via webmaster@gutmedica.com) a few hours ago, did not you?

**Comment by leoanchique** [comment]
Yes I'm I wrote since webmaster@gutmedica.com

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by marcelotorres** [comment]
let's talk by email, as soon as we solve the problem I write the solution here.

**Comment by leoanchique** [comment]
Hi Marcelo I'm waiting you help.

I'm so sorry

Télécharger Outlook pour Android<https://aka.ms/ghei36>

________________________________

**Comment by marcelotorres** [comment]
I disabled the plugin, but the problem continues, so the error is in something else, it has no relation to the plugin.
